FILTER_REGEX_INCLUDE: (src/|Dockerfile|Jenkinsfile|pom\.xml|\.mega-linter\.yml)

ADDITIONAL_EXCLUDED_DIRECTORIES:
  - .mvn
  - logs
  - target
  - megalinter-reports

JAVA_CHECKSTYLE_CONFIG_FILE: google_checks.xml
JAVA_PMD_CONFIG_FILE: .megalinter/pmd-rules.xml
SPELL_CSPELL_CONFIG_FILE: .megalinter/cspell.json

YAML_V8R_FILTER_REGEX_EXCLUDE: (\.mega-linter\.yml)

MARKDOWN_SUMMARY_REPORTER: true
TEXT_REPORTER: true
SARIF_REPORTER: true
